# Generated by Django 2.0.1 on 2018-02-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180212_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('repo_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
