# Generated by Django 2.0.1 on 2018-02-20 07:34

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_repodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=login.models.user_directory_path),
        ),
    ]
