# Generated by Django 2.0.1 on 2018-02-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180220_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='repository',
        ),
    ]
